# Generated by Django 4.2 on 2026-03-17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medicaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(blank=True, max_length=20, unique=True)),
                ("date_vente", models.DateTimeField(default=django.utils.timezone.now)),
                ("total_ttc", models.DecimalField(decimal_places=2, default="0.00", max_digits=12)),
                (
                    "statut",
                    models.CharField(
                        choices=[("EN_COURS", "En cours"), ("COMPLETEE", "Complétée"), ("ANNULEE", "Annulée")],
                        default="COMPLETEE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("est_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Vente",
                "verbose_name_plural": "Ventes",
                "ordering": ["-date_vente", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LigneVente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantite", models.PositiveIntegerField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sous_total", models.DecimalField(decimal_places=2, default="0.00", max_digits=12)),
                (
                    "medicament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_vente",
                        to="medicaments.medicament",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lignes", to="ventes.vente"),
                ),
            ],
            options={
                "verbose_name": "Ligne de vente",
                "verbose_name_plural": "Lignes de vente",
            },
        ),
    ]
